// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b2beauty/notification/broker/sms.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Sms_Priority

typedef GPB_ENUM(Sms_Priority) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Sms_Priority_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Sms_Priority_Normal = 0,
  Sms_Priority_High = 1,
};

GPBEnumDescriptor *Sms_Priority_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Sms_Priority_IsValidValue(int32_t value);

#pragma mark - SmsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SmsRoot : GPBRootObject
@end

#pragma mark - Sms

typedef GPB_ENUM(Sms_FieldNumber) {
  Sms_FieldNumber_Priority = 1,
  Sms_FieldNumber_From = 2,
  Sms_FieldNumber_To = 3,
  Sms_FieldNumber_Message = 4,
};

@interface Sms : GPBMessage

@property(nonatomic, readwrite) Sms_Priority priority;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c Sms's @c priority property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Sms_Priority_RawValue(Sms *message);
/**
 * Sets the raw value of an @c Sms's @c priority property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSms_Priority_RawValue(Sms *message, int32_t value);

#pragma mark - SmsReply

typedef GPB_ENUM(SmsReply_FieldNumber) {
  SmsReply_FieldNumber_Id_p = 1,
};

@interface SmsReply : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
