// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b2beauty/tracking/tracking.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class B2BTypeLocation;
GPB_ENUM_FWD_DECLARE(B2BTypeDevicePlatform);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum B2BTrackingAction

typedef GPB_ENUM(B2BTrackingAction) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  B2BTrackingAction_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  B2BTrackingAction_Signup = 0,
  B2BTrackingAction_Appointment = 1,
};

GPBEnumDescriptor *B2BTrackingAction_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL B2BTrackingAction_IsValidValue(int32_t value);

#pragma mark - B2BTrackingTrackingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface B2BTrackingTrackingRoot : GPBRootObject
@end

#pragma mark - B2BTrackingUserLocationRequest

typedef GPB_ENUM(B2BTrackingUserLocationRequest_FieldNumber) {
  B2BTrackingUserLocationRequest_FieldNumber_Platform = 1,
  B2BTrackingUserLocationRequest_FieldNumber_Location = 2,
  B2BTrackingUserLocationRequest_FieldNumber_Action = 3,
  B2BTrackingUserLocationRequest_FieldNumber_UserId = 4,
  B2BTrackingUserLocationRequest_FieldNumber_BusinessId = 5,
  B2BTrackingUserLocationRequest_FieldNumber_AppointmentId = 6,
};

@interface B2BTrackingUserLocationRequest : GPBMessage

@property(nonatomic, readwrite) enum B2BTypeDevicePlatform platform;

@property(nonatomic, readwrite, strong, null_resettable) B2BTypeLocation *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite) B2BTrackingAction action;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *businessId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appointmentId;

@end

/**
 * Fetches the raw value of a @c B2BTrackingUserLocationRequest's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t B2BTrackingUserLocationRequest_Platform_RawValue(B2BTrackingUserLocationRequest *message);
/**
 * Sets the raw value of an @c B2BTrackingUserLocationRequest's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetB2BTrackingUserLocationRequest_Platform_RawValue(B2BTrackingUserLocationRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c B2BTrackingUserLocationRequest's @c action property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t B2BTrackingUserLocationRequest_Action_RawValue(B2BTrackingUserLocationRequest *message);
/**
 * Sets the raw value of an @c B2BTrackingUserLocationRequest's @c action property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetB2BTrackingUserLocationRequest_Action_RawValue(B2BTrackingUserLocationRequest *message, int32_t value);

#pragma mark - B2BTrackingUserLocationResponse

typedef GPB_ENUM(B2BTrackingUserLocationResponse_FieldNumber) {
  B2BTrackingUserLocationResponse_FieldNumber_Success = 1,
  B2BTrackingUserLocationResponse_FieldNumber_Id_p = 2,
  B2BTrackingUserLocationResponse_FieldNumber_Errors = 3,
};

@interface B2BTrackingUserLocationResponse : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *errors;
/** The number of items in @c errors without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger errors_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
