// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b2beauty/geofencing/geofencing.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class B2BGeofencingGeofence;
@class B2BTypeLocation;
GPB_ENUM_FWD_DECLARE(B2BTypeDevicePlatform);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum B2BGeofencingTransition

typedef GPB_ENUM(B2BGeofencingTransition) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  B2BGeofencingTransition_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  B2BGeofencingTransition_Enter = 0,
  B2BGeofencingTransition_Dwell = 1,
  B2BGeofencingTransition_Exit = 2,
};

GPBEnumDescriptor *B2BGeofencingTransition_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL B2BGeofencingTransition_IsValidValue(int32_t value);

#pragma mark - B2BGeofencingGeofencingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface B2BGeofencingGeofencingRoot : GPBRootObject
@end

#pragma mark - B2BGeofencingCreateEventRequest

typedef GPB_ENUM(B2BGeofencingCreateEventRequest_FieldNumber) {
  B2BGeofencingCreateEventRequest_FieldNumber_Platform = 1,
  B2BGeofencingCreateEventRequest_FieldNumber_Location = 2,
  B2BGeofencingCreateEventRequest_FieldNumber_Transition = 3,
  B2BGeofencingCreateEventRequest_FieldNumber_Name = 4,
  B2BGeofencingCreateEventRequest_FieldNumber_UserId = 5,
  B2BGeofencingCreateEventRequest_FieldNumber_BusinessId = 6,
  B2BGeofencingCreateEventRequest_FieldNumber_AppointmentId = 7,
};

@interface B2BGeofencingCreateEventRequest : GPBMessage

@property(nonatomic, readwrite) enum B2BTypeDevicePlatform platform;

@property(nonatomic, readwrite, strong, null_resettable) B2BTypeLocation *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite) B2BGeofencingTransition transition;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *businessId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appointmentId;

@end

/**
 * Fetches the raw value of a @c B2BGeofencingCreateEventRequest's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t B2BGeofencingCreateEventRequest_Platform_RawValue(B2BGeofencingCreateEventRequest *message);
/**
 * Sets the raw value of an @c B2BGeofencingCreateEventRequest's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetB2BGeofencingCreateEventRequest_Platform_RawValue(B2BGeofencingCreateEventRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c B2BGeofencingCreateEventRequest's @c transition property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t B2BGeofencingCreateEventRequest_Transition_RawValue(B2BGeofencingCreateEventRequest *message);
/**
 * Sets the raw value of an @c B2BGeofencingCreateEventRequest's @c transition property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetB2BGeofencingCreateEventRequest_Transition_RawValue(B2BGeofencingCreateEventRequest *message, int32_t value);

#pragma mark - B2BGeofencingCreateEventResponse

typedef GPB_ENUM(B2BGeofencingCreateEventResponse_FieldNumber) {
  B2BGeofencingCreateEventResponse_FieldNumber_Success = 1,
  B2BGeofencingCreateEventResponse_FieldNumber_Id_p = 2,
  B2BGeofencingCreateEventResponse_FieldNumber_Errors = 3,
};

@interface B2BGeofencingCreateEventResponse : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *errors;
/** The number of items in @c errors without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger errors_Count;

@end

#pragma mark - B2BGeofencingListGeofencesRequest

@interface B2BGeofencingListGeofencesRequest : GPBMessage

@end

#pragma mark - B2BGeofencingListGeofencesResponse

typedef GPB_ENUM(B2BGeofencingListGeofencesResponse_FieldNumber) {
  B2BGeofencingListGeofencesResponse_FieldNumber_GeofencesArray = 1,
};

@interface B2BGeofencingListGeofencesResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<B2BGeofencingGeofence*> *geofencesArray;
/** The number of items in @c geofencesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger geofencesArray_Count;

@end

#pragma mark - B2BGeofencingGeofence

typedef GPB_ENUM(B2BGeofencingGeofence_FieldNumber) {
  B2BGeofencingGeofence_FieldNumber_Id_p = 1,
  B2BGeofencingGeofence_FieldNumber_Name = 2,
  B2BGeofencingGeofence_FieldNumber_StartDate = 3,
  B2BGeofencingGeofence_FieldNumber_EndDate = 4,
  B2BGeofencingGeofence_FieldNumber_Location = 5,
  B2BGeofencingGeofence_FieldNumber_Radius = 6,
};

@interface B2BGeofencingGeofence : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int32_t startDate;

@property(nonatomic, readwrite) int32_t endDate;

@property(nonatomic, readwrite, strong, null_resettable) B2BTypeLocation *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

/** in meters */
@property(nonatomic, readwrite) uint32_t radius;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
